Med 101 implement availability api
ZenBit-Tech/MedOn_be pull request #18
Opened 2023-05-08 03:00 UTC by Mati-Pereira

# Availability API

### Features

- Availability api to get, create and delete(changing in future)

**PR checklist:**

Common
- [x] types for input and output params
- [x]  no any, should be also added to eslint rules
- [x]  try/catch for any async function
- [x] no magic numbers
- [x]  compare only with constants not with strings
(instead of user === ‘admin’, better user === roles.admin)
- [x]  no ternary operator inside ternary operator (bad example: question ? first:
second ? third: fourth)
- [x]  avoid similar types with duplicating by generics
- [x]  no console.log in pr
- [x]  .env file should be in .gitignore
- [x]  delete commented code if it's not part of documentation
- [x]  no links in the code, env links should be in env file (for example: server url),
constant links (for example default avatar URL) should be in constant file
- [x]  constants and function names should be lowercase.
- [x]  no dates format in the code (like "dd/MM/yyyy”), move it in global constant
variable
- [x]  import rules. imports should come in a specific order: node modules, absolute
path, relative path
- [x]  strings should be in the constant variable. Example: instead of ‘15 3 * * *’,
const EACH_DAY_15h_15min = ‘15 3 * * *’

1.2 Backend
- [x]  swagger for each endpoint
- [x]  less requests to db, all data should be taken with one query
- [x]  public in method use only is use function externally
- [x] use ConfigService instead of process.env

2023-05-08 12:30 UTC, skazzp requested changes

2023-05-08 13:15 UTC, skazzp requested changes

2023-05-08 13:15 UTC, skazzp commented on src/modules/availability/availability.service.ts
> +        if (existingAvailability.length > 0) {
I don't think we should use approach to map requests to DB, better set needed columns to unique. Or select all data once and check it.

2023-05-10 14:54 UTC, whiteadam2 approved these changes

2023-05-10 15:01 UTC, skazzp approved these changes

2023-05-10 16:39 UTC, skazzp approved these changes

2023-05-15 16:30 UTC, lyudad approved these changes

2023-05-15 16:38 UTC, merged